import type { NoveraDatabase } from '@novera/database';
import type { QuestView } from '@novera/shared';
export class ProgressionService{
 constructor(private readonly db:NoveraDatabase){}
 async state(characterId:bigint):Promise<{quests:QuestView[];achievements:any[]}>{const[q]=await this.db.pool.query<any[]>('SELECT quest_key,stage,status,progress FROM quest_progress WHERE character_id=? ORDER BY started_at DESC',[characterId]);const[a]=await this.db.pool.query<any[]>('SELECT achievement_key,progress,unlocked_at FROM achievements WHERE character_id=?',[characterId]);return{quests:q.map(r=>({key:r.quest_key,stage:r.stage,status:r.status,progress:this.json(r.progress)})),achievements:a.map(r=>({key:r.achievement_key,progress:Number(r.progress),unlockedAt:r.unlocked_at?new Date(r.unlocked_at).toISOString():null}))}}
 async startQuest(characterId:bigint,key:string):Promise<boolean>{if(!/^[a-z0-9_.-]{3,64}$/i.test(key))return false;await this.db.pool.execute('INSERT INTO quest_progress(character_id,quest_key) VALUES(?,?) ON DUPLICATE KEY UPDATE quest_key=quest_key',[characterId,key]);return true}
 async advanceQuest(characterId:bigint,key:string,stage:string,progress:Record<string,unknown>,complete=false):Promise<void>{if(!/^[a-z0-9_.-]{1,64}$/i.test(stage))throw new Error('invalid quest stage');await this.db.pool.execute('UPDATE quest_progress SET stage=?,progress=?,status=?,completed_at=? WHERE character_id=? AND quest_key=?',[stage,JSON.stringify(progress),complete?'completed':'active',complete?new Date():null,characterId,key])}
 async addAchievementProgress(characterId:bigint,key:string,delta:number,target:number):Promise<void>{if(!Number.isSafeInteger(delta)||delta<=0||!Number.isSafeInteger(target)||target<=0)return;await this.db.pool.execute('INSERT INTO achievements(character_id,achievement_key,progress,unlocked_at) VALUES(?,?,?,IF(? >= ?,NOW(),NULL)) ON DUPLICATE KEY UPDATE progress=LEAST(VALUES(progress)+progress,?),unlocked_at=IF(unlocked_at IS NULL AND progress+? >= ?,NOW(),unlocked_at)',[characterId,key,delta,delta,target,target,delta,target])}
 private json(v:unknown):Record<string,unknown>{if(!v)return{};if(typeof v==='object')return v as Record<string,unknown>;try{return JSON.parse(String(v))}catch{return{}}}
}
