import type { NoveraDatabase } from '@novera/database';
import type { PhoneContactView, PhoneMessageView } from '@novera/shared';

export class PhoneService {
  constructor(private readonly db:NoveraDatabase) {}
  async contacts(characterId:bigint):Promise<PhoneContactView[]> { const [rows]=await this.db.pool.query<any[]>('SELECT id, contact_character_id, alias FROM phone_contacts WHERE character_id=? ORDER BY alias',[characterId]); return rows.map(r=>({id:String(r.id),characterId:String(r.contact_character_id),alias:r.alias})); }
  async addContact(characterId:bigint,targetId:bigint,alias:string):Promise<boolean>{ if(characterId===targetId||alias.trim().length<1||alias.trim().length>64)return false; const [targets]=await this.db.pool.query<any[]>('SELECT id FROM characters WHERE id=? AND deleted_at IS NULL LIMIT 1',[targetId]); if(!targets[0])return false; await this.db.pool.execute('INSERT INTO phone_contacts(character_id,contact_character_id,alias) VALUES(?,?,?) ON DUPLICATE KEY UPDATE alias=VALUES(alias)',[characterId,targetId,alias.trim()]); return true; }
  async send(sender:bigint,receiver:bigint,body:string):Promise<bigint|null>{ const text=body.trim(); if(sender===receiver||text.length<1||text.length>500)return null; const [targets]=await this.db.pool.query<any[]>('SELECT id FROM characters WHERE id=? AND deleted_at IS NULL LIMIT 1',[receiver]); if(!targets[0])return null; const [result]=await this.db.pool.execute<any>('INSERT INTO phone_messages(sender_character_id,receiver_character_id,body) VALUES(?,?,?)',[sender,receiver,text]); return BigInt(result.insertId); }
  async conversation(a:bigint,b:bigint,limit=100):Promise<PhoneMessageView[]>{ const safe=Math.max(1,Math.min(100,Math.trunc(limit))); const [rows]=await this.db.pool.query<any[]>('SELECT id,sender_character_id,receiver_character_id,body,created_at,read_at FROM phone_messages WHERE (sender_character_id=? AND receiver_character_id=?) OR (sender_character_id=? AND receiver_character_id=?) ORDER BY created_at DESC LIMIT ?',[a,b,b,a,safe]); return rows.reverse().map(r=>({id:String(r.id),senderId:String(r.sender_character_id),receiverId:String(r.receiver_character_id),body:r.body,createdAt:new Date(r.created_at).toISOString(),readAt:r.read_at?new Date(r.read_at).toISOString():null})); }
}
