import type { NoveraDatabase } from '@novera/database';
import type { FineView } from '@novera/shared';

export class GovernmentService {
  constructor(private readonly db:NoveraDatabase) {}
  async fines(characterId:bigint):Promise<FineView[]>{ const [rows]=await this.db.pool.query<any[]>('SELECT id,amount,reason,status,created_at FROM fines WHERE character_id=? ORDER BY created_at DESC LIMIT 100',[characterId]); return rows.map(r=>({id:String(r.id),amount:Number(r.amount),reason:r.reason,status:r.status,createdAt:new Date(r.created_at).toISOString()})); }
  async issueFine(targetId:bigint,issuerId:bigint,amount:number,reason:string):Promise<bigint|null>{ const text=reason.trim(); if(!Number.isSafeInteger(amount)||amount<50||amount>1_000_000||text.length<3||text.length>190)return null; const [result]=await this.db.pool.execute<any>('INSERT INTO fines(character_id,issuer_character_id,amount,reason) VALUES(?,?,?,?)',[targetId,issuerId,amount,text]); return BigInt(result.insertId); }
  async payFine(characterId:bigint,fineId:bigint):Promise<boolean>{ const c=await this.db.pool.getConnection(); try{await c.beginTransaction();const [rows]=await c.query<any[]>('SELECT amount,status FROM fines WHERE id=? AND character_id=? FOR UPDATE',[fineId,characterId]);const f=rows[0];if(!f||f.status!=='unpaid'){await c.rollback();return false;}await c.execute('INSERT IGNORE INTO character_wallets(character_id) VALUES(?)',[characterId]);const [paid]=await c.execute<any>('UPDATE character_wallets SET bank=bank-? WHERE character_id=? AND bank>=?',[f.amount,characterId,f.amount]);if(paid.affectedRows!==1){await c.rollback();return false;}await c.execute('UPDATE fines SET status="paid",paid_at=NOW() WHERE id=?',[fineId]);await c.execute('INSERT INTO money_transactions(character_id,type,amount,metadata) VALUES(?,?,?,JSON_OBJECT("fineId",?))',[characterId,'fine_payment',-Number(f.amount),fineId.toString()]);await c.commit();return true;}catch(e){await c.rollback();throw e;}finally{c.release();}}
}
