import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const runtime = resolve(root, 'runtime');
const required = ['conf.json','packages/novera/index.js','client_packages/index.js','client_packages/novera/client/index.js','migrations/0001_accounts.sql','migrations/0002_character_creator.sql','migrations/0003_gameplay_core.sql'];
for (const file of required) await access(resolve(runtime, file));
const conf = JSON.parse(await readFile(resolve(runtime, 'conf.json'), 'utf8'));
if (conf.name !== 'NOVERA RP') throw new Error('runtime conf.json has wrong server name');
if (Number(conf.maxplayers) !== 500) throw new Error('runtime conf.json must use 500 slots');
console.log('NOVERA runtime validation passed');
